### ISSUE TITLE
Not optimizing JPG images

### ISSUE THREAD

**Issue by M-Gonzalo** [rbrito/pdfsizeopt#7]
I can't make pdfsizeopt process JPG images, even when I set ECT with options. Am I doing something wrong, or is pdfsizeopt simply not designed to do this?
Thanks in advance for any reply

**Comment by zvezdochiot** [comment]
Hi @M-Gonzalo .

See https://github.com/rbrito/scripts/blob/master/optimize_pdfs.py

**Comment by M-Gonzalo** [comment]
> Hi @M-Gonzalo .
> 
> See [rbrito/scripts@`master`/optimize_pdfs.py](https://github.com/rbrito/scripts/blob/master/optimize_pdfs.py?rgh-link-date=2021-12-13T15%3A07%3A41Z)

Thanks for your reply @zvezdochiot 
I downloaded the script and installed the dependencies (except for the patched version of jpgcrush as I won't be doing cross-fs operations) but I'm getting an error. I'm not proficient enough in python to debug it

```
...

INFO:root:    **** Removed name: /Metadata from obj 3671.
INFO:root:    **** Removed name: /Info from obj 3676.
INFO:root:    **** Removed name: /EmbeddedFiles from obj 3677.
Traceback (most recent call last):
  File "/home/gonzalo/pdfsizeopt/./optimize_pdfs.py", line 315, in <module>
    perform_optimizations(tmpdirname, filename, args.remove_js)
  File "/home/gonzalo/pdfsizeopt/./optimize_pdfs.py", line 232, in perform_optimizations
    delete_metadata(my_pdf, remove_js)
  File "/home/gonzalo/pdfsizeopt/./optimize_pdfs.py", line 281, in delete_metadata
    delete_name(my_pdf.root, name)
AttributeError: 'pikepdf._qpdf.Pdf' object has no attribute 'root'
```
Any clue as to what is happening?
I also replaced jpgcrush with ect inside the script just in case the patched version was really necessary but the errors are exactly the same

**Comment by zvezdochiot** [comment]
Hi @M-Gonzalo .

No. I can't tell you about the script. I can only suggest another solution. 

Some formatting of the pdf structure will be required.  (https://github.com/ksharindam/pdfcook)

```sh
./pdfcook you_name_file.pdf file.pdf
mkdir po; csplit -n 4 -f po/obj. file.pdf /obj/ /endobj/1 '{*}'
cd po
mkdir j; for tf in *; do [ "$(grep DCTDecode $tf)" ] && mv -v $tf j; done
cd j
for tf in obj.*; do csplit -f $tf.s. $tf /stream/1 /endstream/; done
for tf in *.s.01; do cp -fv $tf $tf.jpg; done
```
After jpeg optimization, rebuilding pdf is a little more complicated.
